### ISSUE TITLE
Performance, Accessibility, Browser Testing

### ISSUE THREAD

**Issue by dasi0075** [dasi0075/animal-rescue-website#1]
Hi Charlie, I tried the testing thing I don't know how to do everything on my own.

Main issue for me is how to make my logo stay without moving. Markbot asked me for embed and embed16by9 so anyways got lost on that one, tried to fix it after submitting to Markbot but is not helping.
@charlie-quinn

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded.`

⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
@dasi0075 ⚠️`Reminder: please close this issue since it has been resolved or expired.`

**Comment by charlie-quinn** [comment]
@dasi0075 ⚠️`Reminder: please close this issue since it has been resolved or expired.`
