### ISSUE TITLE
Request for Grades

### ISSUE THREAD

**Issue by dasi0075** [dasi0075/animal-rescue-website#2]
@charlie_quinn
If it were for Markbot, my grade would be A because all was green and adjusted accordingly. 
I like the style of my website but know for sure improvements need to be made (especially in the logo placement I always struggle with that same issue). 
Didn't do the testing because I won't have the time to do it before deadline, but I coded on time and did everything that was required so I would give myself a B for all the 20hrs + spent on this last assignment and pre-prod of photos and designs of logos etc.

Nadia

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your college email address.`

⚠️`Reminder: please close this issue once it has been resolved.`
